[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-120
monitor_port = /dev/cu.usbserial-120

lib_deps =
    ./lib_composite_color_rgb
    SD

build_flags =
    -O2
    -Wno-error=deprecated-declarations
